<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
    <line>
      <![CDATA[this is my reporter log]]>
    </line>
  </reporter-output>
  <suite name="ExtentReprot" duration-ms="44" started-at="2018-07-17T07:00:10Z" finished-at="2018-07-17T07:00:10Z">
    <groups>
    </groups>
    <test name="TestEx" duration-ms="44" started-at="2018-07-17T07:00:10Z" finished-at="2018-07-17T07:00:10Z">
      <class name="com.reports.TestReport">
        <test-method status="PASS" signature="test1()[pri:0, instance:com.reports.TestReport@4520ebad]" name="test1" duration-ms="14" started-at="2018-07-17T15:00:10Z" finished-at="2018-07-17T15:00:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.reports.TestReport@4520ebad]" name="test2" duration-ms="1" started-at="2018-07-17T15:00:10Z" finished-at="2018-07-17T15:00:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test3()[pri:0, instance:com.reports.TestReport@4520ebad]" name="test3" duration-ms="3" started-at="2018-07-17T15:00:10Z" finished-at="2018-07-17T15:00:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="FAIL" signature="testReport()[pri:0, instance:com.reports.TestReport@4520ebad]" name="testReport" duration-ms="2" started-at="2018-07-17T15:00:10Z" finished-at="2018-07-17T15:00:10Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[this is my runtime exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: this is my runtime exception
	at com.reports.TestReport.testReport(TestReport.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
            <line>
              <![CDATA[this is my reporter log]]>
            </line>
          </reporter-output>
        </test-method> <!-- testReport -->
      </class> <!-- com.reports.TestReport -->
    </test> <!-- TestEx -->
  </suite> <!-- ExtentReprot -->
</testng-results>
